package com.thinkinjava.myjava.chap15;

public enum Watercolors {
    ZINC,LEMO_YELLO,MEDIUM_YELLO,DEEP_YELLO,ORANGE,
    BRILLIANT_RED,CRIMSON,MAGENTA,ROSE_MADDER,VIOLET,
    CERULEN_BLUE_HUE,PHTHALO_BLUE,ULTRAMARINE,
    COBALT_BLUE_HUW,PERMANENT_GREEN,VIRIDIAN_HUE,
    SAP_GREEN,YELLOW_OCHRE,BURNT_SIENNA,RAW_UMBER,
    BURNT_UMBER,PAYNES_GRAY,IVORY_BLACK
}
